package projecteuler

// DistinctPowers - Calcalates number of unique terms generated by
// all a^b, 2<=a<=100 & 2<=b<=100
func DistinctPowers() int {
	cache := make(map[string]int, 0)
	for a := 2; a < 101; a++ {
		for b := 2; b < 101; b++ {
			tmp := powerOf(int64(a), int64(b))
			if _, ok := cache[tmp]; !ok {
				cache[tmp] = 1
			}
		}
	}
	return len(cache)
}
